<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/HRComments/Comment.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0ce4ac1ffb9fd41c268e5e3aa9d222c7)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_HRComments_DAO_Comment constructor.
 */
class CRM_HRComments_DAO_Comment extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrcomments_comment';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique Comment ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * The Entity name associated with the comment
   *
   * @var string
   */
  public $entity_name;
  /**
   * The Entity ID associated with the comment
   *
   * @var int unsigned
   */
  public $entity_id;
  /**
   * The comment field
   *
   * @var text
   */
  public $text;
  /**
   * FK to the contact who made the comment
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * The date and time the comment was added
   *
   * @var datetime
   */
  public $created_at;
  /**
   * Whether this comment has been deleted or not
   *
   * @var boolean
   */
  public $is_deleted;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_hrcomments_comment';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique Comment ID',
          'required' => true,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
        'entity_name' => array(
          'name' => 'entity_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity Name') ,
          'description' => 'The Entity name associated with the comment',
          'required' => true,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
        'entity_id' => array(
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'The Entity ID associated with the comment',
          'required' => true,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
        'text' => array(
          'name' => 'text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Text') ,
          'description' => 'The comment field',
          'required' => true,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
        'contact_id' => array(
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to the contact who made the comment',
          'required' => true,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'created_at' => array(
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Created At') ,
          'description' => 'The date and time the comment was added',
          'required' => true,
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
        'is_deleted' => array(
          'name' => 'is_deleted',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Whether this comment has been deleted or not',
          'table_name' => 'civicrm_hrcomments_comment',
          'entity' => 'Comment',
          'bao' => 'CRM_HRComments_DAO_Comment',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrcomments_comment', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrcomments_comment', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array(
      'index_entity_id_entity_name' => array(
        'name' => 'index_entity_id_entity_name',
        'field' => array(
          0 => 'entity_id',
          1 => 'entity_name',
        ) ,
        'localizable' => false,
        'sig' => 'civicrm_hrcomments_comment::0::entity_id::entity_name',
      ) ,
    );
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
