<?xml version="1.0" encoding="iso-8859-1" ?>

<CustomData>
  <CustomGroups>
    <CustomGroup>
      <name>Emergency_Contact</name>
      <title>Emergency Contact</title>
      <extends>Relationship</extends>
      <extends_entity_column_value_option_group>relationship_type</extends_entity_column_value_option_group>
      <extends_entity_column_value_option_value></extends_entity_column_value_option_value>
      <extends_entity_column_value>:;:;:;{$hremerg_relationship_type_id}:;:;:;</extends_entity_column_value>
      <style>Inline</style>
      <collapse_display>0</collapse_display>
      <help_pre></help_pre>
      <help_post></help_post>
      <weight>8</weight>
      <is_active>1</is_active>
      <table_name>civicrm_value_emergency_contact_11</table_name>
      <is_multiple>0</is_multiple>
      <collapse_adv_display>0</collapse_adv_display>
      <created_date>0000-00-00 00:00:00</created_date>
    </CustomGroup>
  </CustomGroups>
  <CustomFields>
    <CustomField>
      <name>Priority</name>
      <label>Priority</label>
      <data_type>String</data_type>
      <html_type>Select</html_type>
      <is_required>0</is_required>
      <is_searchable>0</is_searchable>
      <is_search_range>0</is_search_range>
      <weight>8</weight>
      <is_active>1</is_active>
      <is_view>0</is_view>
      <text_length>128</text_length>
      <note_columns>60</note_columns>
      <note_rows>4</note_rows>
      <column_name>priority_44</column_name>
      <option_group_name>priority_20130514082429</option_group_name>
      <custom_group_name>Emergency_Contact</custom_group_name>
    </CustomField>
  </CustomFields>
  <OptionGroups>
    <OptionGroup>
      <name>priority_20130514082429</name>
      <title>Priority</title>
      <is_reserved>1</is_reserved>
      <is_active>1</is_active>
    </OptionGroup>
  </OptionGroups>
  <OptionValues>
    <OptionValue>
      <label>Primary</label>
      <value>Primary</value>
      <name>Primary</name>
      <is_default>0</is_default>
      <weight>1</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>priority_20130514082429</option_group_name>
    </OptionValue>
    <OptionValue>
      <label>Secondary</label>
      <value>Secondary</value>
      <name>Secondary</name>
      <is_default>0</is_default>
      <weight>2</weight>
      <is_optgroup>0</is_optgroup>
      <is_reserved>0</is_reserved>
      <is_active>1</is_active>
      <option_group_name>priority_20130514082429</option_group_name>
    </OptionValue>
  </OptionValues>
</CustomData>
