<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/ContactWorkPattern.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:703647f767679e4cfba89e0976b2fcfd)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern constructor.
 */
class CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_contact_work_pattern';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique ContactWorkPattern ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to the Contact representing the employee
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * FK to the Work Pattern linked to an employee
   *
   * @var int unsigned
   */
  public $pattern_id;
  /**
   * The date this work pattern will start to be considered active
   *
   * @var date
   */
  public $effective_date;
  /**
   * The date this work pattern will stop being considered active
   *
   * @var date
   */
  public $effective_end_date;
  /**
   * One of the values of the Job Contract Revision Change Reason option group
   *
   * @var string
   */
  public $change_reason;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_contact_work_pattern';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'pattern_id', 'civicrm_hrleaveandabsences_work_pattern', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique ContactWorkPattern ID',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
        ) ,
        'contact_id' => array(
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to the Contact representing the employee',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'pattern_id' => array(
          'name' => 'pattern_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to the Work Pattern linked to an employee',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
        ) ,
        'effective_date' => array(
          'name' => 'effective_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Effective Date') ,
          'description' => 'The date this work pattern will start to be considered active',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
        ) ,
        'effective_end_date' => array(
          'name' => 'effective_end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Effective End Date') ,
          'description' => 'The date this work pattern will stop being considered active',
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
        ) ,
        'change_reason' => array(
          'name' => 'change_reason',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Change Reason') ,
          'description' => 'One of the values of the Job Contract Revision Change Reason option group',
          'maxlength' => 512,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_contact_work_pattern',
          'entity' => 'ContactWorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_ContactWorkPattern',
          'pseudoconstant' => array(
            'optionGroupName' => 'hrjc_revision_change_reason',
            'optionEditPath' => 'civicrm/admin/options/hrjc_revision_change_reason',
          )
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_contact_work_pattern', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_contact_work_pattern', $prefix, array());
    return $r;
  }
}
