<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2016                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2016
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/Entitlement.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
class CRM_HRLeaveAndAbsences_DAO_Entitlement extends CRM_Core_DAO
{
  /**
   * static instance to hold the table name
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_entitlement';
  /**
   * static instance to hold the field values
   *
   * @var array
   */
  static $_fields = null;
  /**
   * static instance to hold the keys used in $_fields for each field.
   *
   * @var array
   */
  static $_fieldKeys = null;
  /**
   * static instance to hold the FK relationships
   *
   * @var string
   */
  static $_links = null;
  /**
   * static instance to hold the values that can
   * be imported
   *
   * @var array
   */
  static $_import = null;
  /**
   * static instance to hold the values that can
   * be exported
   *
   * @var array
   */
  static $_export = null;
  /**
   * static value to see if we should log any modifications to
   * this table in the civicrm_log table
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique Entitlement ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to AbsencePeriod
   *
   * @var int unsigned
   */
  public $period_id;
  /**
   * FK to AbsenceType
   *
   * @var int unsigned
   */
  public $type_id;
  /**
   * FK to HRJobContract
   *
   * @var int unsigned
   */
  public $contract_id;
  /**
   * The number of days proposed for this entitlement
   *
   * @var float
   */
  public $proposed_entitlement;
  /**
   * The number of days brought forward from the previous period
   *
   * @var float
   */
  public $brought_forward_days;
  /**
   * The date the brought forward days will expire
   *
   * @var date
   */
  public $brought_forward_expiration_date;
  /**
   * The pro rata calculated for this entitlement period
   *
   * @var float
   */
  public $pro_rata;
  /**
   * Indicates if the proposed_entitlement was overridden
   *
   * @var boolean
   */
  public $overridden;
  /**
   * The comment added by the user about the calculation for this entitlement
   *
   * @var text
   */
  public $comment;
  /**
   * FK to Contact. The contact that represents the used the added the comment to this entitlement
   *
   * @var int unsigned
   */
  public $comment_author_id;
  /**
   * The date and time the comment for this entitlement was added/updated
   *
   * @var datetime
   */
  public $comment_updated_at;
  /**
   * class constructor
   *
   * @return civicrm_hrleaveandabsences_entitlement
   */
  function __construct()
  {
    $this->__table = 'civicrm_hrleaveandabsences_entitlement';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns()
  {
    if (!self::$_links) {
      self::$_links = static ::createReferenceColumns(__CLASS__);
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'period_id', 'civicrm_hrleaveandabsences_absence_period', 'id');
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'type_id', 'civicrm_hrleaveandabsences_absence_type', 'id');
      self::$_links[] = new CRM_Core_Reference_Basic(self::getTableName() , 'comment_author_id', 'civicrm_contact', 'id');
    }
    return self::$_links;
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields()
  {
    if (!(self::$_fields)) {
      self::$_fields = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique Entitlement ID',
          'required' => true,
        ) ,
        'period_id' => array(
          'name' => 'period_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to AbsencePeriod',
          'required' => true,
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_AbsencePeriod',
        ) ,
        'type_id' => array(
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to AbsenceType',
          'required' => true,
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_AbsenceType',
        ) ,
        'contract_id' => array(
          'name' => 'contract_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to HRJobContract',
          'required' => true,
        ) ,
        'proposed_entitlement' => array(
          'name' => 'proposed_entitlement',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Proposed Entitlement') ,
          'description' => 'The number of days proposed for this entitlement',
          'required' => true,
          'precision' => array(
            20,
            2
          ) ,
        ) ,
        'brought_forward_days' => array(
          'name' => 'brought_forward_days',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Brought Forward Days') ,
          'description' => 'The number of days brought forward from the previous period',
          'precision' => array(
            20,
            2
          ) ,
        ) ,
        'brought_forward_expiration_date' => array(
          'name' => 'brought_forward_expiration_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Brought Forward Expiration Date') ,
          'description' => 'The date the brought forward days will expire',
        ) ,
        'pro_rata' => array(
          'name' => 'pro_rata',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Pro Rata') ,
          'description' => 'The pro rata calculated for this entitlement period',
          'precision' => array(
            20,
            2
          ) ,
        ) ,
        'overridden' => array(
          'name' => 'overridden',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Overridden') ,
          'description' => 'Indicates if the proposed_entitlement was overridden',
          'default' => 'false',
        ) ,
        'comment' => array(
          'name' => 'comment',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Comment') ,
          'description' => 'The comment added by the user about the calculation for this entitlement',
        ) ,
        'comment_author_id' => array(
          'name' => 'comment_author_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact. The contact that represents the used the added the comment to this entitlement',
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'comment_updated_at' => array(
          'name' => 'comment_updated_at',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Comment Updated At') ,
          'description' => 'The date and time the comment for this entitlement was added/updated',
        ) ,
      );
    }
    return self::$_fields;
  }
  /**
   * Returns an array containing, for each field, the arary key used for that
   * field in self::$_fields.
   *
   * @return array
   */
  static function &fieldKeys()
  {
    if (!(self::$_fieldKeys)) {
      self::$_fieldKeys = array(
        'id' => 'id',
        'period_id' => 'period_id',
        'type_id' => 'type_id',
        'contract_id' => 'contract_id',
        'proposed_entitlement' => 'proposed_entitlement',
        'brought_forward_days' => 'brought_forward_days',
        'brought_forward_expiration_date' => 'brought_forward_expiration_date',
        'pro_rata' => 'pro_rata',
        'overridden' => 'overridden',
        'comment' => 'comment',
        'comment_author_id' => 'comment_author_id',
        'comment_updated_at' => 'comment_updated_at',
      );
    }
    return self::$_fieldKeys;
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName()
  {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog()
  {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false)
  {
    if (!(self::$_import)) {
      self::$_import = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('import', $field)) {
          if ($prefix) {
            self::$_import['hrleaveandabsences_entitlement'] = & $fields[$name];
          } else {
            self::$_import[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_import;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false)
  {
    if (!(self::$_export)) {
      self::$_export = array();
      $fields = self::fields();
      foreach($fields as $name => $field) {
        if (CRM_Utils_Array::value('export', $field)) {
          if ($prefix) {
            self::$_export['hrleaveandabsences_entitlement'] = & $fields[$name];
          } else {
            self::$_export[$name] = & $fields[$name];
          }
        }
      }
    }
    return self::$_export;
  }
}
