<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/LeaveRequestCalendarFeedConfig.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e8fad8f0d13bd0fe2ffd83153da38606)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig constructor.
 */
class CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_calendar_feed_config';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique LeaveRequestCalendarFeedConfig ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * The Calendar Feed Config Title. There cannot be more than one entity with the same title
   *
   * @var string
   */
  public $title;
  /**
   * The Calendar Feed Config Timezone
   *
   * @var string
   */
  public $timezone;
  /**
   * The Calendar Feed Config Hash. Should be unique per config
   *
   * @var string
   */
  public $hash;
  /**
   * Whether the feed is active or not
   *
   * @var boolean
   */
  public $is_active;
  /**
   * The date and time this Calendar Feed Config was created
   *
   * @var datetime
   */
  public $created_date;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_calendar_feed_config';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique LeaveRequestCalendarFeedConfig ID',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
        'title' => array(
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Title') ,
          'description' => 'The Calendar Feed Config Title. There cannot be more than one entity with the same title',
          'required' => true,
          'maxlength' => 127,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
        'timezone' => array(
          'name' => 'timezone',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Timezone') ,
          'description' => 'The Calendar Feed Config Timezone',
          'required' => true,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
        'hash' => array(
          'name' => 'hash',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Hash') ,
          'description' => 'The Calendar Feed Config Hash. Should be unique per config',
          'required' => true,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
        'is_active' => array(
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Whether the feed is active or not',
          'default' => '1',
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
        'created_date' => array(
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Created Date') ,
          'description' => 'The date and time this Calendar Feed Config was created',
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_calendar_feed_config', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_calendar_feed_config', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array();
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
