<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /vagrant/hr-bugs-4002/sites/all/modules/civicrm/tools/extensions/civihr/uk.co.compucorp.civicrm.hrleaveandabsences/xml/schema/CRM/HRLeaveAndAbsences/LeaveRequestCalendarFeedConfig.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:5b2bca398649a1ac0e73fac97105c9f9)
 */

/**
 * Database access object for the LeaveRequestCalendarFeedConfig entity.
 */
class CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_calendar_feed_config';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique LeaveRequestCalendarFeedConfig ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * The Calendar Feed Config Title. There cannot be more than one entity with the same title
   *
   * @var string
   */
  public $title;

  /**
   * The Calendar Feed Config Timezone
   *
   * @var string
   */
  public $timezone;

  /**
   * The Calendar Feed Config Hash. Should be unique per config
   *
   * @var string
   */
  public $hash;

  /**
   * The components of the leave request feed, e.g leave types, departments
   *
   * @var text
   */
  public $composed_of;

  /**
   * Who gets to view the feed link e.g staff in certain departments or location
   *
   * @var text
   */
  public $visible_to;

  /**
   * Whether the feed is active or not
   *
   * @var boolean
   */
  public $is_active;

  /**
   * The date and time this Calendar Feed Config was created
   *
   * @var datetime
   */
  public $created_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_calendar_feed_config';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique LeaveRequestCalendarFeedConfig ID',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Title'),
          'description' => 'The Calendar Feed Config Title. There cannot be more than one entity with the same title',
          'required' => TRUE,
          'maxlength' => 127,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'timezone' => [
          'name' => 'timezone',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Timezone'),
          'description' => 'The Calendar Feed Config Timezone',
          'required' => TRUE,
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'hash' => [
          'name' => 'hash',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Hash'),
          'description' => 'The Calendar Feed Config Hash. Should be unique per config',
          'required' => TRUE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'composed_of' => [
          'name' => 'composed_of',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Composed Of'),
          'description' => 'The components of the leave request feed, e.g leave types, departments',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'visible_to' => [
          'name' => 'visible_to',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Visible To'),
          'description' => 'Who gets to view the feed link e.g staff in certain departments or location',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => 'Whether the feed is active or not',
          'required' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Created Date'),
          'description' => 'The date and time this Calendar Feed Config was created',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_calendar_feed_config',
          'entity' => 'LeaveRequestCalendarFeedConfig',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveRequestCalendarFeedConfig',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_calendar_feed_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_calendar_feed_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'unique_calendar_title' => [
        'name' => 'unique_calendar_title',
        'field' => [
          0 => 'title',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_hrleaveandabsences_calendar_feed_config::1::title',
      ],
      'unique_calendar_hash' => [
        'name' => 'unique_calendar_hash',
        'field' => [
          0 => 'hash',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_hrleaveandabsences_calendar_feed_config::1::hash',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
