<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/LeaveBalanceChange.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:19377e0ef50e29865e145f30fff0921f)
 */

/**
 * Database access object for the LeaveBalanceChange entity.
 */
class CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_leave_balance_change';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique LeaveBalanceChange ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * One of the values of the Leave Balance Type option group
   *
   * @var int unsigned
   */
  public $type_id;

  /**
   * The amount of days this change in balance represents to the entitlement
   *
   * @var float
   */
  public $amount;

  /**
   * Some balance changes can expire. This is the date it will expire.
   *
   * @var date
   */
  public $expiry_date;

  /**
   * FK to LeaveBalanceChange. This is only used for a balance change that represents expired days, and it will be related to the balance change that has expired.
   *
   * @var int unsigned
   */
  public $expired_balance_change_id;

  /**
   * Some balance changes are originated from an specific source (a leave request date, for example) and this field will have the ID of this source.
   *
   * @var int unsigned
   */
  public $source_id;

  /**
   * Some balance changes are originated from an specific source (a leave request date, for example) and this field will have text string to indicate what is the source.
   *
   * @var string
   */
  public $source_type;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_leave_balance_change';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'expired_balance_change_id', 'civicrm_hrleaveandabsences_leave_balance_change', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique LeaveBalanceChange ID',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
        ],
        'type_id' => [
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'One of the values of the Leave Balance Type option group',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'hrleaveandabsences_leave_balance_change_type',
            'optionEditPath' => 'civicrm/admin/options/hrleaveandabsences_leave_balance_change_type',
          ]
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Amount'),
          'description' => 'The amount of days this change in balance represents to the entitlement',
          'required' => TRUE,
          'precision' => [
            20,
            2
          ],
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
        ],
        'expiry_date' => [
          'name' => 'expiry_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Expiry Date'),
          'description' => 'Some balance changes can expire. This is the date it will expire.',
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
        ],
        'expired_balance_change_id' => [
          'name' => 'expired_balance_change_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to LeaveBalanceChange. This is only used for a balance change that represents expired days, and it will be related to the balance change that has expired.',
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
        ],
        'source_id' => [
          'name' => 'source_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Some balance changes are originated from an specific source (a leave request date, for example) and this field will have the ID of this source.',
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
        ],
        'source_type' => [
          'name' => 'source_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Source Type'),
          'description' => 'Some balance changes are originated from an specific source (a leave request date, for example) and this field will have text string to indicate what is the source.',
          'maxlength' => 20,
          'size' => CRM_Utils_Type::MEDIUM,
          'table_name' => 'civicrm_hrleaveandabsences_leave_balance_change',
          'entity' => 'LeaveBalanceChange',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeaveBalanceChange',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_leave_balance_change', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_leave_balance_change', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'unique_expiry_record' => [
        'name' => 'unique_expiry_record',
        'field' => [
          0 => 'expired_balance_change_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_hrleaveandabsences_leave_balance_change::1::expired_balance_change_id',
      ],
      'index_source_id' => [
        'name' => 'index_source_id',
        'field' => [
          0 => 'source_id',
          1 => 'source_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hrleaveandabsences_leave_balance_change::0::source_id::source_type',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
