<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/LeavePeriodEntitlement.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:956c8d5a63ddaff0056cdd0574d9b379)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement constructor.
 */
class CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_leave_period_entitlement';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique Leave Period Entitlement ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to AbsencePeriod
   *
   * @var int unsigned
   */
  public $period_id;
  /**
   * FK to AbsenceType
   *
   * @var int unsigned
   */
  public $type_id;
  /**
   * FK to Contact (civicrm_contact)
   *
   * @var int unsigned
   */
  public $contact_id;
  /**
   * Indicates if the entitlement was overridden
   *
   * @var boolean
   */
  public $overridden;
  /**
   * The comment added by the user about the calculation for this entitlement
   *
   * @var text
   */
  public $comment;
  /**
   * FK to Contact. The contact that represents the user who added the comment to this entitlement
   *
   * @var int unsigned
   */
  public $comment_author_id;
  /**
   * The date and time the comment for this entitlement was added/updated
   *
   * @var datetime
   */
  public $comment_date;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_leave_period_entitlement';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'period_id', 'civicrm_hrleaveandabsences_absence_period', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'type_id', 'civicrm_hrleaveandabsences_absence_type', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'comment_author_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique Leave Period Entitlement ID',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
        ) ,
        'period_id' => array(
          'name' => 'period_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to AbsencePeriod',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_AbsencePeriod',
        ) ,
        'type_id' => array(
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to AbsenceType',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
          'FKClassName' => 'CRM_HRLeaveAndAbsences_DAO_AbsenceType',
        ) ,
        'contact_id' => array(
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact (civicrm_contact)',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'overridden' => array(
          'name' => 'overridden',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Overridden') ,
          'description' => 'Indicates if the entitlement was overridden',
          'default' => 'false',
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
        ) ,
        'comment' => array(
          'name' => 'comment',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Comment') ,
          'description' => 'The comment added by the user about the calculation for this entitlement',
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
        ) ,
        'comment_author_id' => array(
          'name' => 'comment_author_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact. The contact that represents the user who added the comment to this entitlement',
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ) ,
        'comment_date' => array(
          'name' => 'comment_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Comment Date') ,
          'description' => 'The date and time the comment for this entitlement was added/updated',
          'table_name' => 'civicrm_hrleaveandabsences_leave_period_entitlement',
          'entity' => 'LeavePeriodEntitlement',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_LeavePeriodEntitlement',
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_leave_period_entitlement', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_leave_period_entitlement', $prefix, array());
    return $r;
  }
}
