<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/PublicHoliday.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a680d166a2100d15eb45fed3c659be67)
 */

/**
 * Database access object for the PublicHoliday entity.
 */
class CRM_HRLeaveAndAbsences_DAO_PublicHoliday extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_public_holiday';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique PublicHoliday ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * The Public Holiday title
   *
   * @var string
   */
  public $title;

  /**
   * The date of Public Holiday. There can't be more than one Public Holiday on the same date
   *
   * @var date
   */
  public $date;

  /**
   * Determines if Public Holiday entry is active. The is_active name is used to follow Civi's conventions
   *
   * @var boolean
   */
  public $is_active;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_public_holiday';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique PublicHoliday ID',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_public_holiday',
          'entity' => 'PublicHoliday',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_PublicHoliday',
          'localizable' => 0,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Title'),
          'description' => 'The Public Holiday title',
          'required' => TRUE,
          'maxlength' => 127,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_public_holiday',
          'entity' => 'PublicHoliday',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_PublicHoliday',
          'localizable' => 0,
        ],
        'date' => [
          'name' => 'date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Date'),
          'description' => 'The date of Public Holiday. There can\'t be more than one Public Holiday on the same date',
          'required' => TRUE,
          'table_name' => 'civicrm_hrleaveandabsences_public_holiday',
          'entity' => 'PublicHoliday',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_PublicHoliday',
          'localizable' => 0,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is enabled?'),
          'description' => 'Determines if Public Holiday entry is active. The is_active name is used to follow Civi\'s conventions',
          'default' => '1',
          'table_name' => 'civicrm_hrleaveandabsences_public_holiday',
          'entity' => 'PublicHoliday',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_PublicHoliday',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_public_holiday', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_public_holiday', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'unique_date' => [
        'name' => 'unique_date',
        'field' => [
          0 => 'date',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_hrleaveandabsences_public_holiday::1::date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
