<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/HRLeaveAndAbsences/WorkPattern.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:5e9f0159337944ca31e57db538d28c89)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_HRLeaveAndAbsences_DAO_WorkPattern constructor.
 */
class CRM_HRLeaveAndAbsences_DAO_WorkPattern extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_hrleaveandabsences_work_pattern';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique WorkPattern ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * The Work Pattern label's (name)
   *
   * @var string
   */
  public $label;
  /**
   * A small description of the Work Pattern
   *
   * @var string
   */
  public $description;
  /**
   * There can only be one default entity at any given time
   *
   * @var boolean
   */
  public $is_default;
  /**
   * Only enabled Work Patterns can be used. The is_active name is used to follow Civi's conventions.
   *
   * @var boolean
   */
  public $is_active;
  /**
   * The weight value is used to order the Work Patterns on a list
   *
   * @var int unsigned
   */
  public $weight;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_hrleaveandabsences_work_pattern';
    parent::__construct();
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique WorkPattern ID',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
        'label' => array(
          'name' => 'label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Label') ,
          'description' => 'The Work Pattern label\'s (name)',
          'required' => true,
          'maxlength' => 127,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
        'description' => array(
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Description') ,
          'description' => 'A small description of the Work Pattern',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
        'is_default' => array(
          'name' => 'is_default',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is default?') ,
          'description' => 'There can only be one default entity at any given time',
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
        'is_active' => array(
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('Is enabled?') ,
          'description' => 'Only enabled Work Patterns can be used. The is_active name is used to follow Civi\'s conventions.',
          'default' => '1',
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
        'weight' => array(
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Weight') ,
          'description' => 'The weight value is used to order the Work Patterns on a list',
          'required' => true,
          'table_name' => 'civicrm_hrleaveandabsences_work_pattern',
          'entity' => 'WorkPattern',
          'bao' => 'CRM_HRLeaveAndAbsences_DAO_WorkPattern',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hrleaveandabsences_work_pattern', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hrleaveandabsences_work_pattern', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array(
      'work_pattern_unique_label' => array(
        'name' => 'work_pattern_unique_label',
        'field' => array(
          0 => 'label',
        ) ,
        'localizable' => false,
        'unique' => true,
        'sig' => 'civicrm_hrleaveandabsences_work_pattern::1::label',
      ) ,
    );
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
