DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_brought_forward`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_entitlement`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_notification_receiver`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_absence_type`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_day`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_week`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_pattern`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_absence_period`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_public_holiday`;
