-- +--------------------------------------------------------------------+
-- | CiviCRM version 5                                                  |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2018                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_week`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_pattern`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_work_day`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_public_holiday`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_notification_receiver`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_request_date`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_calendar_feed_config`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_request`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_period_entitlement_log`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_period_entitlement`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_balance_change_expiry_log`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_leave_balance_change`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_contact_work_pattern`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_absence_type`;
DROP TABLE IF EXISTS `civicrm_hrleaveandabsences_absence_period`;

SET FOREIGN_KEY_CHECKS=1;
