SET foreign_key_checks = 0;
TRUNCATE civicrm_hrjobcontract_revision;
TRUNCATE civicrm_hrjobcontract_details;
TRUNCATE civicrm_hrjobcontract_health;
TRUNCATE civicrm_hrjobcontract_hour;
TRUNCATE civicrm_hrjobcontract_leave;
TRUNCATE civicrm_hrjobcontract_pay;
TRUNCATE civicrm_hrjobcontract_pension;
TRUNCATE civicrm_hrjobcontract_role;
TRUNCATE civicrm_hrjobcontract;
DELETE FROM `civicrm_relationship` WHERE contact_id_a = 202 AND contact_id_b = 203 and civicrm_relationship.relationship_type_id = (SELECT rt.id FROM `civicrm_relationship_type` rt WHERE rt.name_a_b = 'has Leave Approved By');
SET foreign_key_checks = 1;
